theme: jekyll-theme-dinky
title: Sayma Sultana
description: PhD student at Wayne State University
image: https://www.google.com/search?q=flower&sxsrf=ALeKk01jikjR69y4RrCV7j03v_1R_L39qQ:1610649458185&tbm=isch&source=iu&ictx=1&fir=4eM3sPu0zHHglM%252CZih9vqAzJOmeTM%252C_&vet=1&usg=AI4_-kR4btZb4K-kthsXpQTJJjqQ-zfxPw&sa=X&ved=2ahUKEwjG4b_miJzuAhUYCM0KHUg1DOIQ9QF6BAgOEAE&biw=1280&bih=578&dpr=1.5#imgrc=4eM3sPu0zHHglM
